### ISSUE TITLE
Batch?

### ISSUE THREAD

**Issue by oleg-yudovich** [pusher/pusher-channels-chunking-example#2]
https://github.com/pusher/pusher-channels-chunking-example/blob/0a7cc6726b2b163bb99092ae5aa33b731b38e987/pusher-http-node/chunked.js#L8

Why not to send all chunks in one batch request here?

**Comment by oleg-yudovich** [comment]
I see comment. Sorry

**Comment by jameshfisher** [comment]
PRs welcome! :-)
